# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/cmd.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproto/cmd.proto\x12\x07rts.cmd\"\xc2\x02\n\x07\x43ommand\x12$\n\x04move\x18\x01 \x01(\x0b\x32\x14.rts.cmd.MoveCommandH\x00\x12(\n\x06\x61ttack\x18\x02 \x01(\x0b\x32\x16.rts.cmd.AttackCommandH\x00\x12&\n\x05\x62uild\x18\x03 \x01(\x0b\x32\x15.rts.cmd.BuildCommandH\x00\x12(\n\x06gather\x18\x04 \x01(\x0b\x32\x16.rts.cmd.GatherCommandH\x00\x12,\n\x08research\x18\x05 \x01(\x0b\x32\x18.rts.cmd.ResearchCommandH\x00\x12&\n\x05train\x18\x06 \x01(\x0b\x32\x15.rts.cmd.TrainCommandH\x00\x12$\n\x04stop\x18\x07 \x01(\x0b\x32\x14.rts.cmd.StopCommandH\x00\x12\x0e\n\x06issuer\x18\n \x01(\x05\x42\t\n\x07payload\"E\n\x0c\x43ommandBatch\x12\"\n\x08\x63ommands\x18\x01 \x03(\x0b\x32\x10.rts.cmd.Command\x12\x11\n\tgame_tick\x18\x02 \x01(\x05\"B\n\x0bMoveCommand\x12\x0f\n\x07unit_id\x18\x01 \x01(\t\x12\x10\n\x08target_x\x18\x02 \x01(\x02\x12\x10\n\x08target_y\x18\x03 \x01(\x02\"7\n\rAttackCommand\x12\x13\n\x0b\x61ttacker_id\x18\x01 \x01(\t\x12\x11\n\ttarget_id\x18\x02 \x01(\t\"W\n\x0c\x42uildCommand\x12\x12\n\nbuilder_id\x18\x01 \x01(\t\x12\x15\n\rbuilding_type\x18\x02 \x01(\t\x12\r\n\x05pos_x\x18\x03 \x01(\x02\x12\r\n\x05pos_y\x18\x04 \x01(\x02\"7\n\rGatherCommand\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x13\n\x0bresource_id\x18\x02 \x01(\t\"<\n\x0fResearchCommand\x12\x13\n\x0b\x62uilding_id\x18\x01 \x01(\t\x12\x14\n\x0cupgrade_name\x18\x02 \x01(\t\"6\n\x0cTrainCommand\x12\x13\n\x0b\x62uilding_id\x18\x01 \x01(\t\x12\x11\n\tunit_type\x18\x02 \x01(\t\"\x1e\n\x0bStopCommand\x12\x0f\n\x07unit_id\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.cmd_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_COMMAND']._serialized_start=29
  _globals['_COMMAND']._serialized_end=351
  _globals['_COMMANDBATCH']._serialized_start=353
  _globals['_COMMANDBATCH']._serialized_end=422
  _globals['_MOVECOMMAND']._serialized_start=424
  _globals['_MOVECOMMAND']._serialized_end=490
  _globals['_ATTACKCOMMAND']._serialized_start=492
  _globals['_ATTACKCOMMAND']._serialized_end=547
  _globals['_BUILDCOMMAND']._serialized_start=549
  _globals['_BUILDCOMMAND']._serialized_end=636
  _globals['_GATHERCOMMAND']._serialized_start=638
  _globals['_GATHERCOMMAND']._serialized_end=693
  _globals['_RESEARCHCOMMAND']._serialized_start=695
  _globals['_RESEARCHCOMMAND']._serialized_end=755
  _globals['_TRAINCOMMAND']._serialized_start=757
  _globals['_TRAINCOMMAND']._serialized_end=811
  _globals['_STOPCOMMAND']._serialized_start=813
  _globals['_STOPCOMMAND']._serialized_end=843
# @@protoc_insertion_point(module_scope)
