# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import obs_pb2 as proto_dot_obs__pb2
from . import cmd_pb2 as proto_dot_cmd__pb2
from . import state_pb2 as proto_dot_state__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13proto/service.proto\x12\x0brts.service\x1a\x0fproto/obs.proto\x1a\x0fproto/cmd.proto\x1a\x11proto/state.proto\"9\n\x10StartGameRequest\x12%\n\x06\x63onfig\x18\x01 \x01(\x0b\x32\x15.rts.state.GameConfig\"\x11\n\x0fGetStateRequest\"%\n\x10GetReplayRequest\x12\x11\n\tfrom_tick\x18\x01 \x01(\x05\"\x0f\n\rHealthRequest\"D\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x11\n\tgame_tick\x18\x02 \x01(\x05\x12\x0e\n\x06status\x18\x03 \x01(\t2\xee\x02\n\x0eSimCoreService\x12H\n\tStartGame\x12\x1d.rts.service.StartGameRequest\x1a\x1c.rts.state.GameStateSnapshot\x12;\n\x04Step\x12\x15.rts.cmd.CommandBatch\x1a\x1c.rts.state.GameStateSnapshot\x12\x46\n\x08GetState\x12\x1c.rts.service.GetStateRequest\x1a\x1c.rts.state.GameStateSnapshot\x12J\n\tGetReplay\x12\x1d.rts.service.GetReplayRequest\x1a\x1c.rts.state.GameStateSnapshot0\x01\x12\x41\n\x06Health\x12\x1a.rts.service.HealthRequest\x1a\x1b.rts.service.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STARTGAMEREQUEST']._serialized_start=89
  _globals['_STARTGAMEREQUEST']._serialized_end=146
  _globals['_GETSTATEREQUEST']._serialized_start=148
  _globals['_GETSTATEREQUEST']._serialized_end=165
  _globals['_GETREPLAYREQUEST']._serialized_start=167
  _globals['_GETREPLAYREQUEST']._serialized_end=204
  _globals['_HEALTHREQUEST']._serialized_start=206
  _globals['_HEALTHREQUEST']._serialized_end=221
  _globals['_HEALTHRESPONSE']._serialized_start=223
  _globals['_HEALTHRESPONSE']._serialized_end=291
  _globals['_SIMCORESERVICE']._serialized_start=294
  _globals['_SIMCORESERVICE']._serialized_end=660
# @@protoc_insertion_point(module_scope)
