# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import cmd_pb2 as proto_dot_cmd__pb2
from . import service_pb2 as proto_dot_service__pb2
from . import state_pb2 as proto_dot_state__pb2


class SimCoreServiceStub(object):
    """─── SimCore gRPC 服务 ───

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartGame = channel.unary_unary(
                '/rts.service.SimCoreService/StartGame',
                request_serializer=proto_dot_service__pb2.StartGameRequest.SerializeToString,
                response_deserializer=proto_dot_state__pb2.GameStateSnapshot.FromString,
                )
        self.Step = channel.unary_unary(
                '/rts.service.SimCoreService/Step',
                request_serializer=proto_dot_cmd__pb2.CommandBatch.SerializeToString,
                response_deserializer=proto_dot_state__pb2.GameStateSnapshot.FromString,
                )
        self.GetState = channel.unary_unary(
                '/rts.service.SimCoreService/GetState',
                request_serializer=proto_dot_service__pb2.GetStateRequest.SerializeToString,
                response_deserializer=proto_dot_state__pb2.GameStateSnapshot.FromString,
                )
        self.GetReplay = channel.unary_stream(
                '/rts.service.SimCoreService/GetReplay',
                request_serializer=proto_dot_service__pb2.GetReplayRequest.SerializeToString,
                response_deserializer=proto_dot_state__pb2.GameStateSnapshot.FromString,
                )
        self.Health = channel.unary_unary(
                '/rts.service.SimCoreService/Health',
                request_serializer=proto_dot_service__pb2.HealthRequest.SerializeToString,
                response_deserializer=proto_dot_service__pb2.HealthResponse.FromString,
                )


class SimCoreServiceServicer(object):
    """─── SimCore gRPC 服务 ───

    """

    def StartGame(self, request, context):
        """Start a new game, returns initial state snapshot (unary)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Step(self, request, context):
        """Submit commands for the next tick (unary)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Get the full current state (unary)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplay(self, request, context):
        """Stream replay from a given tick (server-streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check (unary)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimCoreServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartGame': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGame,
                    request_deserializer=proto_dot_service__pb2.StartGameRequest.FromString,
                    response_serializer=proto_dot_state__pb2.GameStateSnapshot.SerializeToString,
            ),
            'Step': grpc.unary_unary_rpc_method_handler(
                    servicer.Step,
                    request_deserializer=proto_dot_cmd__pb2.CommandBatch.FromString,
                    response_serializer=proto_dot_state__pb2.GameStateSnapshot.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=proto_dot_service__pb2.GetStateRequest.FromString,
                    response_serializer=proto_dot_state__pb2.GameStateSnapshot.SerializeToString,
            ),
            'GetReplay': grpc.unary_stream_rpc_method_handler(
                    servicer.GetReplay,
                    request_deserializer=proto_dot_service__pb2.GetReplayRequest.FromString,
                    response_serializer=proto_dot_state__pb2.GameStateSnapshot.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=proto_dot_service__pb2.HealthRequest.FromString,
                    response_serializer=proto_dot_service__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rts.service.SimCoreService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimCoreService(object):
    """─── SimCore gRPC 服务 ───

    """

    @staticmethod
    def StartGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rts.service.SimCoreService/StartGame',
            proto_dot_service__pb2.StartGameRequest.SerializeToString,
            proto_dot_state__pb2.GameStateSnapshot.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Step(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rts.service.SimCoreService/Step',
            proto_dot_cmd__pb2.CommandBatch.SerializeToString,
            proto_dot_state__pb2.GameStateSnapshot.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rts.service.SimCoreService/GetState',
            proto_dot_service__pb2.GetStateRequest.SerializeToString,
            proto_dot_state__pb2.GameStateSnapshot.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetReplay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/rts.service.SimCoreService/GetReplay',
            proto_dot_service__pb2.GetReplayRequest.SerializeToString,
            proto_dot_state__pb2.GameStateSnapshot.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rts.service.SimCoreService/Health',
            proto_dot_service__pb2.HealthRequest.SerializeToString,
            proto_dot_service__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
