# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/state.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/state.proto\x12\trts.state\"\xf2\x02\n\x11GameStateSnapshot\x12\x11\n\tgame_tick\x18\x01 \x01(\x05\x12\x13\n\x0bis_terminal\x18\x02 \x01(\x08\x12\x0e\n\x06winner\x18\x03 \x01(\x05\x12\x1a\n\x12termination_reason\x18\x04 \x01(\t\x12(\n\x08\x65ntities\x18\x05 \x03(\x0b\x32\x16.rts.state.EntityState\x12>\n\tresources\x18\x06 \x03(\x0b\x32+.rts.state.GameStateSnapshot.ResourcesEntry\x12\"\n\x06\x66og_p1\x18\x07 \x01(\x0b\x32\x12.rts.state.FogGrid\x12\"\n\x06\x66og_p2\x18\x08 \x01(\x0b\x32\x12.rts.state.FogGrid\x12%\n\x06\x63onfig\x18\t \x01(\x0b\x32\x15.rts.state.GameConfig\x1a\x30\n\x0eResourcesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\xbe\x02\n\x0b\x45ntityState\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05owner\x18\x02 \x01(\x05\x12\x13\n\x0b\x65ntity_type\x18\x03 \x01(\t\x12\r\n\x05pos_x\x18\x04 \x01(\x02\x12\r\n\x05pos_y\x18\x05 \x01(\x02\x12\x0e\n\x06health\x18\x06 \x01(\x05\x12\x12\n\nmax_health\x18\x07 \x01(\x05\x12\r\n\x05speed\x18\x08 \x01(\x02\x12\x0e\n\x06\x61ttack\x18\t \x01(\x02\x12\x14\n\x0c\x61ttack_range\x18\n \x01(\x02\x12\x0f\n\x07is_idle\x18\x0b \x01(\x08\x12\x14\n\x0c\x63\x61rry_amount\x18\x0c \x01(\x02\x12\x17\n\x0fis_constructing\x18\r \x01(\x08\x12\x18\n\x10production_queue\x18\x0e \x03(\t\x12\x15\n\rresource_type\x18\x0f \x01(\t\x12\x17\n\x0fresource_amount\x18\x10 \x01(\x02\";\n\x07\x46ogGrid\x12\x11\n\x05tiles\x18\x01 \x03(\x05\x42\x02\x10\x01\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\"~\n\nGameConfig\x12\x10\n\x08map_seed\x18\x01 \x01(\x05\x12\x11\n\tmap_width\x18\x02 \x01(\x05\x12\x12\n\nmap_height\x18\x03 \x01(\x05\x12\x11\n\tmax_ticks\x18\x04 \x01(\x05\x12\x11\n\ttick_rate\x18\x05 \x01(\x02\x12\x11\n\tgame_mode\x18\x06 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.state_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GAMESTATESNAPSHOT_RESOURCESENTRY']._options = None
  _globals['_GAMESTATESNAPSHOT_RESOURCESENTRY']._serialized_options = b'8\001'
  _globals['_FOGGRID'].fields_by_name['tiles']._options = None
  _globals['_FOGGRID'].fields_by_name['tiles']._serialized_options = b'\020\001'
  _globals['_GAMESTATESNAPSHOT']._serialized_start=33
  _globals['_GAMESTATESNAPSHOT']._serialized_end=403
  _globals['_GAMESTATESNAPSHOT_RESOURCESENTRY']._serialized_start=355
  _globals['_GAMESTATESNAPSHOT_RESOURCESENTRY']._serialized_end=403
  _globals['_ENTITYSTATE']._serialized_start=406
  _globals['_ENTITYSTATE']._serialized_end=724
  _globals['_FOGGRID']._serialized_start=726
  _globals['_FOGGRID']._serialized_end=785
  _globals['_GAMECONFIG']._serialized_start=787
  _globals['_GAMECONFIG']._serialized_end=913
# @@protoc_insertion_point(module_scope)
